//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4984
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 日报模板.Weather {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="Weather.WeatherWebServiceSoap")]
    public interface WeatherWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportCity(string byProvinceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getSupportProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getSupportDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getSupportDataSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getWeatherbyCityName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getWeatherbyCityName(string theCityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getWeatherbyCityNamePro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getWeatherbyCityNamePro(string theCityName, string theUserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceSoapChannel : 日报模板.Weather.WeatherWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceSoapClient : System.ServiceModel.ClientBase<日报模板.Weather.WeatherWebServiceSoap>, 日报模板.Weather.WeatherWebServiceSoap {
        
        public WeatherWebServiceSoapClient() {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getSupportCity(string byProvinceName) {
            return base.Channel.getSupportCity(byProvinceName);
        }
        
        public string[] getSupportProvince() {
            return base.Channel.getSupportProvince();
        }
        
        public System.Data.DataSet getSupportDataSet() {
            return base.Channel.getSupportDataSet();
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            return base.Channel.getWeatherbyCityName(theCityName);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            return base.Channel.getWeatherbyCityNamePro(theCityName, theUserID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="Weather.WeatherWebServiceHttpGet")]
    public interface WeatherWebServiceHttpGet {
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportCityResponse getSupportCity(日报模板.Weather.getSupportCityRequest request);
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportProvinceResponse getSupportProvince(日报模板.Weather.getSupportProvinceRequest request);
        
        // CODEGEN: 操作 getSupportDataSet 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportDataSetRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getSupportDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportDataSetResponse getSupportDataSet(日报模板.Weather.getSupportDataSetRequest request);
        
        // CODEGEN: 操作 getWeatherbyCityName 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getWeatherbyCityNameResponse getWeatherbyCityName(日报模板.Weather.getWeatherbyCityNameRequest request);
        
        // CODEGEN: 操作 getWeatherbyCityNamePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameProRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpGet/getWeatherbyCityNameProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getWeatherbyCityNameProResponse getWeatherbyCityNamePro(日报模板.Weather.getWeatherbyCityNameProRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest() {
        }
        
        public getSupportCityRequest(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse() {
        }
        
        public getSupportCityResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest {
        
        public getSupportProvinceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse() {
        }
        
        public getSupportProvinceResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetRequest {
        
        public getSupportDataSetRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportDataSetResponse() {
        }
        
        public getSupportDataSetResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        public getWeatherbyCityNameRequest() {
        }
        
        public getWeatherbyCityNameRequest(string theCityName) {
            this.theCityName = theCityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameResponse() {
        }
        
        public getWeatherbyCityNameResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherbyCityNameProRequest() {
        }
        
        public getWeatherbyCityNameProRequest(string theCityName, string theUserID) {
            this.theCityName = theCityName;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameProResponse() {
        }
        
        public getWeatherbyCityNameProResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceHttpGetChannel : 日报模板.Weather.WeatherWebServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceHttpGetClient : System.ServiceModel.ClientBase<日报模板.Weather.WeatherWebServiceHttpGet>, 日报模板.Weather.WeatherWebServiceHttpGet {
        
        public WeatherWebServiceHttpGetClient() {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportCityResponse 日报模板.Weather.WeatherWebServiceHttpGet.getSupportCity(日报模板.Weather.getSupportCityRequest request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            日报模板.Weather.getSupportCityRequest inValue = new 日报模板.Weather.getSupportCityRequest();
            inValue.byProvinceName = byProvinceName;
            日报模板.Weather.getSupportCityResponse retVal = ((日报模板.Weather.WeatherWebServiceHttpGet)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportProvinceResponse 日报模板.Weather.WeatherWebServiceHttpGet.getSupportProvince(日报模板.Weather.getSupportProvinceRequest request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            日报模板.Weather.getSupportProvinceRequest inValue = new 日报模板.Weather.getSupportProvinceRequest();
            日报模板.Weather.getSupportProvinceResponse retVal = ((日报模板.Weather.WeatherWebServiceHttpGet)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportDataSetResponse 日报模板.Weather.WeatherWebServiceHttpGet.getSupportDataSet(日报模板.Weather.getSupportDataSetRequest request) {
            return base.Channel.getSupportDataSet(request);
        }
        
        public System.Data.DataSet getSupportDataSet() {
            日报模板.Weather.getSupportDataSetRequest inValue = new 日报模板.Weather.getSupportDataSetRequest();
            日报模板.Weather.getSupportDataSetResponse retVal = ((日报模板.Weather.WeatherWebServiceHttpGet)(this)).getSupportDataSet(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getWeatherbyCityNameResponse 日报模板.Weather.WeatherWebServiceHttpGet.getWeatherbyCityName(日报模板.Weather.getWeatherbyCityNameRequest request) {
            return base.Channel.getWeatherbyCityName(request);
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            日报模板.Weather.getWeatherbyCityNameRequest inValue = new 日报模板.Weather.getWeatherbyCityNameRequest();
            inValue.theCityName = theCityName;
            日报模板.Weather.getWeatherbyCityNameResponse retVal = ((日报模板.Weather.WeatherWebServiceHttpGet)(this)).getWeatherbyCityName(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getWeatherbyCityNameProResponse 日报模板.Weather.WeatherWebServiceHttpGet.getWeatherbyCityNamePro(日报模板.Weather.getWeatherbyCityNameProRequest request) {
            return base.Channel.getWeatherbyCityNamePro(request);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            日报模板.Weather.getWeatherbyCityNameProRequest inValue = new 日报模板.Weather.getWeatherbyCityNameProRequest();
            inValue.theCityName = theCityName;
            inValue.theUserID = theUserID;
            日报模板.Weather.getWeatherbyCityNameProResponse retVal = ((日报模板.Weather.WeatherWebServiceHttpGet)(this)).getWeatherbyCityNamePro(inValue);
            return retVal.ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="Weather.WeatherWebServiceHttpPost")]
    public interface WeatherWebServiceHttpPost {
        
        // CODEGEN: 操作 getSupportCity 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportCityRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportCityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportCityResponse1 getSupportCity(日报模板.Weather.getSupportCityRequest1 request);
        
        // CODEGEN: 操作 getSupportProvince 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportProvinceRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportProvinceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportProvinceResponse1 getSupportProvince(日报模板.Weather.getSupportProvinceRequest1 request);
        
        // CODEGEN: 操作 getSupportDataSet 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportDataSetRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getSupportDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getSupportDataSetResponse1 getSupportDataSet(日报模板.Weather.getSupportDataSetRequest1 request);
        
        // CODEGEN: 操作 getWeatherbyCityName 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getWeatherbyCityNameResponse1 getWeatherbyCityName(日报模板.Weather.getWeatherbyCityNameRequest1 request);
        
        // CODEGEN: 操作 getWeatherbyCityNamePro 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameProRequest", ReplyAction="http://WebXml.com.cn/WeatherWebServiceHttpPost/getWeatherbyCityNameProResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        日报模板.Weather.getWeatherbyCityNameProResponse1 getWeatherbyCityNamePro(日报模板.Weather.getWeatherbyCityNameProRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string byProvinceName;
        
        public getSupportCityRequest1() {
        }
        
        public getSupportCityRequest1(string byProvinceName) {
            this.byProvinceName = byProvinceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportCityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportCityResponse1() {
        }
        
        public getSupportCityResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceRequest1 {
        
        public getSupportProvinceRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportProvinceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getSupportProvinceResponse1() {
        }
        
        public getSupportProvinceResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetRequest1 {
        
        public getSupportDataSetRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSupportDataSetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getSupportDataSetResponse1() {
        }
        
        public getSupportDataSetResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        public getWeatherbyCityNameRequest1() {
        }
        
        public getWeatherbyCityNameRequest1(string theCityName) {
            this.theCityName = theCityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameResponse1() {
        }
        
        public getWeatherbyCityNameResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string theCityName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string theUserID;
        
        public getWeatherbyCityNameProRequest1() {
        }
        
        public getWeatherbyCityNameProRequest1(string theCityName, string theUserID) {
            this.theCityName = theCityName;
            this.theUserID = theUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherbyCityNameProResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getWeatherbyCityNameProResponse1() {
        }
        
        public getWeatherbyCityNameProResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WeatherWebServiceHttpPostChannel : 日报模板.Weather.WeatherWebServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeatherWebServiceHttpPostClient : System.ServiceModel.ClientBase<日报模板.Weather.WeatherWebServiceHttpPost>, 日报模板.Weather.WeatherWebServiceHttpPost {
        
        public WeatherWebServiceHttpPostClient() {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportCityResponse1 日报模板.Weather.WeatherWebServiceHttpPost.getSupportCity(日报模板.Weather.getSupportCityRequest1 request) {
            return base.Channel.getSupportCity(request);
        }
        
        public string[] getSupportCity(string byProvinceName) {
            日报模板.Weather.getSupportCityRequest1 inValue = new 日报模板.Weather.getSupportCityRequest1();
            inValue.byProvinceName = byProvinceName;
            日报模板.Weather.getSupportCityResponse1 retVal = ((日报模板.Weather.WeatherWebServiceHttpPost)(this)).getSupportCity(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportProvinceResponse1 日报模板.Weather.WeatherWebServiceHttpPost.getSupportProvince(日报模板.Weather.getSupportProvinceRequest1 request) {
            return base.Channel.getSupportProvince(request);
        }
        
        public string[] getSupportProvince() {
            日报模板.Weather.getSupportProvinceRequest1 inValue = new 日报模板.Weather.getSupportProvinceRequest1();
            日报模板.Weather.getSupportProvinceResponse1 retVal = ((日报模板.Weather.WeatherWebServiceHttpPost)(this)).getSupportProvince(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getSupportDataSetResponse1 日报模板.Weather.WeatherWebServiceHttpPost.getSupportDataSet(日报模板.Weather.getSupportDataSetRequest1 request) {
            return base.Channel.getSupportDataSet(request);
        }
        
        public System.Data.DataSet getSupportDataSet() {
            日报模板.Weather.getSupportDataSetRequest1 inValue = new 日报模板.Weather.getSupportDataSetRequest1();
            日报模板.Weather.getSupportDataSetResponse1 retVal = ((日报模板.Weather.WeatherWebServiceHttpPost)(this)).getSupportDataSet(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getWeatherbyCityNameResponse1 日报模板.Weather.WeatherWebServiceHttpPost.getWeatherbyCityName(日报模板.Weather.getWeatherbyCityNameRequest1 request) {
            return base.Channel.getWeatherbyCityName(request);
        }
        
        public string[] getWeatherbyCityName(string theCityName) {
            日报模板.Weather.getWeatherbyCityNameRequest1 inValue = new 日报模板.Weather.getWeatherbyCityNameRequest1();
            inValue.theCityName = theCityName;
            日报模板.Weather.getWeatherbyCityNameResponse1 retVal = ((日报模板.Weather.WeatherWebServiceHttpPost)(this)).getWeatherbyCityName(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        日报模板.Weather.getWeatherbyCityNameProResponse1 日报模板.Weather.WeatherWebServiceHttpPost.getWeatherbyCityNamePro(日报模板.Weather.getWeatherbyCityNameProRequest1 request) {
            return base.Channel.getWeatherbyCityNamePro(request);
        }
        
        public string[] getWeatherbyCityNamePro(string theCityName, string theUserID) {
            日报模板.Weather.getWeatherbyCityNameProRequest1 inValue = new 日报模板.Weather.getWeatherbyCityNameProRequest1();
            inValue.theCityName = theCityName;
            inValue.theUserID = theUserID;
            日报模板.Weather.getWeatherbyCityNameProResponse1 retVal = ((日报模板.Weather.WeatherWebServiceHttpPost)(this)).getWeatherbyCityNamePro(inValue);
            return retVal.ArrayOfString;
        }
    }
}
